// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg-K06YIq7umj215uUHWqkOYdAzCeyLgk',
    appId: '1:276109971919:web:d2bb4b607f9aac57b082ba',
    messagingSenderId: '276109971919',
    projectId: 'csp-app-fdaac',
    authDomain: 'csp-app-fdaac.firebaseapp.com',
    storageBucket: 'csp-app-fdaac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwGWRuhltc1c2T-_3j6-cWpSyQoNTZF68',
    appId: '1:276109971919:android:9a3f3b4ce43ef617b082ba',
    messagingSenderId: '276109971919',
    projectId: 'csp-app-fdaac',
    storageBucket: 'csp-app-fdaac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2hoRZ8bre7WjtiazFXIw_L8p7XpATOyk',
    appId: '1:276109971919:ios:93f52b62ce903b8bb082ba',
    messagingSenderId: '276109971919',
    projectId: 'csp-app-fdaac',
    storageBucket: 'csp-app-fdaac.appspot.com',
    iosClientId: '276109971919-7ubd7ordu0d9lsuen89ftocmdlcn9tr9.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.cspapp',
  );
}
